[package]
name = "peresdev/ui-components"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Ripple = "littensy/ripple@0.10"
Flipper = "reselim/flipper@^2.0.0"
Fusion = "elttob/fusion@0.2.0"
topbarplus = "1foreverhd/topbarplus@3.4.0"
GlassmorphicUI = "boatbomber/glassmorphicui@0.5.1"
ReactOtter = "github.com/Roblox/otter@1.0"
Otter = "github.com/Roblox/otter@1.0"
ReactSpring = "chriscerie/react-spring@<version>"